In [1]:
import numpy as np

In [3]:
matrix = np.array([[7,2,8,11],[44,75,36,23],[91,65,83,17]])
matrix

array([[ 7,  2,  8, 11],
       [44, 75, 36, 23],
       [91, 65, 83, 17]])

## zeros hepsini 0 yapar

In [7]:
zeros=np.zeros([4,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## ones hepsini 1 yapar

In [8]:
ones = np.ones([3,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace 0 dan 100 e kadar olan kısmı eşit 5 parcaya böldü

In [9]:
linspace_arr = np.linspace(0, 100, 5)
linspace_arr

array([  0.,  25.,  50.,  75., 100.])

## eye ana diyagonal kısmını 1 yapar digerlerini 0

In [12]:
eye=np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## add ile toplama işlemi

In [19]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[7,5],[8,9]])
toplam=np.add(matrix1,matrix2)
toplam

array([[ 8,  7],
       [11, 13]])

## subtract ile cıkarma işlemi

In [20]:
cıkarma =np.subtract(matrix1,matrix2)
cıkarma

array([[-6, -3],
       [-5, -5]])

## var ile varyans bulma

In [21]:
varyans =np.var(matrix1)
varyans

1.25

### std ile standart sapma bulma

In [22]:
standart_sapma=np.std(matrix1)
standart_sapma

1.118033988749895

In [25]:
matrix3 = np.array([[3,4],[9,10],[11,12]])
matrix3

array([[ 3,  4],
       [ 9, 10],
       [11, 12]])

## reshape ile tek sütün yapma


In [26]:
matrix3.reshape(6,1)

array([[ 3],
       [ 4],
       [ 9],
       [10],
       [11],
       [12]])

## reshape ile tek satır yapma

In [27]:
matrix3.reshape(1,-1)

array([[ 3,  4,  9, 10, 11, 12]])

## T  ile tranpose alma

In [42]:
matrix3.reshape(1,-1).T

array([[ 3],
       [ 4],
       [ 9],
       [10],
       [11],
       [12]])

In [47]:
matrix = np.array([[7,2,8,11],[44,75,36,23],[91,65,83,17],[1,2,7,8]])
matrix

array([[ 7,  2,  8, 11],
       [44, 75, 36, 23],
       [91, 65, 83, 17],
       [ 1,  2,  7,  8]])

## diagonal ile köşegen alma

In [48]:
matrix.diagonal()

array([ 7, 75, 83,  8])

## determinant hesapla ama için dogru olup olmadıgını printle gösterdim

In [58]:
cıkarma

array([[-6, -3],
       [-5, -5]])

In [59]:
np.linalg.det(cıkarma)

15.0

In [60]:
print(f"{-6*-5} - {-5*-3} = {(-6*-5)-(-5*-3)} ")

30 - 15 = 15 
